name: Onion-Fresh-Links-2024

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours

jobs:
  Onion-Websites-2024:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Delete Onion-Websites-2024.txt
        run: |
          rm -f Onion-Websites-2024.txt
          ls -l  # For debugging purposes, list files in the directory to check if Onion-Websites-2024.txt is deleted
          
      - name: Commit and push changes
        run: |
          git config --global user.email "weichenchoonsa@outlook.com"
          git config --global user.name "choohen4X"
          git add -A  # Add all changes, including the deletion of Onion-Websites-2024.txt
          git commit -m "Onion-Websites-2024.txt" || echo "No changes to commit"
          git push
