name: Onion-Fresh-Links-2024

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours

jobs:
  Onion-Websites-2024:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Update Onion-Websites-2024.txt
        run: |
              echo "$(date -u +'%Y-%m-%d %H:%M:%S') UTC - Update" >> Onion-Websites-2024.txt
          
      - name: Commit changes
        run: |
          git config --global user.email "weichenchoonsa@outlook.com"
          git config --global user.name "choohen4X"
          git add Onion-Websites-2024.txt
          git commit -m "Onion-Websites-2024.txt" || echo "No changes to commit"
          git push
